### ISSUE TITLE
WebSocket connection can't be made after one is disconnected

### ISSUE THREAD

**Issue by ghostdogpr** [polynote/uzhttp#12]
I observe the following behavior: after a Websocket is disconnected, no new connection can be made to the server. That can be reproduced with the example server, using a tool like https://www.websocket.org/echo.html (connect, disconnect, then try to connect again).

Any idea what's happening there?

**Comment by jeremyrsmith** [comment]
Yep, I noticed that too. The websocket thing can end up being very sensitive to interruptions, like if an interruption happens then the whole selector loop gets interrupted. I have a PR up that fixes it I think, at least to some degree. I am not sure how to completely prevent the selector loop from getting interrupted (at least not without preventing the entire app from stopping on SIGTERM), but I hopefully the main issue will be resolved.

**Comment by ghostdogpr** [comment]
I tried with 0.1.2 and it's definitely better, but with some issues still.
- Connect > Disconnect > Connect => seems to work well now.
- Connect > Disconnect > Connect > Disconnect => for some reason, the second Disconnect hangs for 1 minute, then disconnects.

**Comment by ghostdogpr** [comment]
Oh, and once a WebSocket is open, the other endpoints (like a simple GET) don't seem to respond anymore 😅 (maybe this one is my fault, I will double check).

EDIT: it's weird. Doesn't happen with the example code but happens with my code where I do `inputFrames.(...).runDrain.forkDaemon`. As if this was blocking processing.

**Comment by jeremyrsmith** [comment]
How are you generating the output frames? And what are you doing with the input frames?

**Comment by ghostdogpr** [comment]
Output frames come from a queue: `ZStream.fromQueue(sendQueue))`. I consume the input frames in a separate fiber (`forkDaemon`), and sometimes it will offer items to `sendQueue`.

**Comment by ghostdogpr** [comment]
To reproduce:
```scala
case req @ Request.WebsocketRequest(_, uri, _, _, _) if uri.getPath startsWith "/ws" =>
  for {
    queue <- zio.ZQueue.unbounded[Frame]
    ws    <- Response.websocket(req, ZStream.fromQueue(queue))
  } yield ws
```
As soon as I send something inside the websocket from the client side, my other endpoints become unresponsive.

**Comment by ghostdogpr** [comment]
It actually seems `inputFrames` terminates too quickly. It's supposed to be generating items for the whole life of the WebSocket connection, right?

**Comment by jeremyrsmith** [comment]
Yes, if `inputFrames` terminates then something is wrong with the connection. Can you try with debug logging enabled?

**Comment by ghostdogpr** [comment]
Ah, that last issue is happening only with my graphql client. There must be something else, maybe the `Sec-WebSocket-Protocol`. I will dig deeper to find what's causing this, sorry for the confusion. (EDIT: made an issue for that)

Apart from this, what is reproducible easily:
1) with `Response.websocket(req, inputFrames)`, using https://www.websocket.org/echo.html just Connect, Disconnect, Connect, Disconnect  => hangs for 1 minute
Log:
```
[DEBUG]   /ws/graphql?encoding=text 101 Switching Protocols (Unknown size) (74 ms to start)
[DEBUG]   Closing connection
[REQUEST] GET /ws/graphql?encoding=text 101 Switching Protocols (3 s 383 ms to finish, 3 s 457 ms total) (closed)
[DEBUG]   /ws/graphql?encoding=text 101 Switching Protocols (Unknown size) (1 ms to start)
[DEBUG]   Closing connection
[REQUEST] GET /ws/graphql?encoding=text 101 Switching Protocols (1 m to finish, 1 m total) (closed)
```
2) with:
```scala
for {
  _     <- inputFrames.runDrain.onExit(exit => zio.UIO(println(exit))).forkDaemon
  queue <- zio.ZQueue.unbounded[Frame]
  ws    <- Response.websocket(req, ZStream.fromQueue(queue))
} yield ws
```
using https://www.websocket.org/echo.html just Connect, Disconnect  => hangs for 1 minute then doesn't accept new connections
Log:
```
[DEBUG]   /ws/graphql?encoding=text 101 Switching Protocols (Unknown size) (80 ms to start)
[DEBUG]   Closing connection
```

**Comment by jeremyrsmith** [comment]
@ghostdogpr 

I think the issue you're seeing with the echo test is that you're not doing anything with the input frames. The library does nothing for you, so it's up to you to handle `Close` frames, for example – if you don't do that, the client might never actually disconnect (if it waits for a responding `Close` frame). For me, it looks like Chrome (or the Javascript on that test page) doesn't actually close the connection, even after receiving a `Close` frame, which means you also have to handle stopping the stream after sending the `Close` response.

Here's a test that seems to work fine:

```scala
  case req @ Request.WebsocketRequest(_, uri, _, _, inputFrames) if uri.getPath startsWith "/ws" =>
    for {
      ws    <- Response.websocket(req, Stream.flatten(inputFrames.mapM(handleWebsocketFrame)).unTake)
    } yield ws
```

Where `handleWebsocketFrame` looks like this:

```scala

  private def handleWebsocketFrame(frame: Frame): UIO[Stream[Nothing, Take[Nothing, Frame]]] = frame match {
    case frame@Binary(data, _)       => log(s"Binary frame: 0x${formatHex(data)}") as Stream(Take.Value(frame))
    case frame@Text(data, _)         => log(s"Text frame: $data") as Stream(Take.Value(frame))
    case frame@Continuation(data, _) => log(s"Continuation frame: 0x${formatHex(data)}") as Stream(Take.Value(frame))
    case Ping => log("Ping!") as Stream(Take.Value(Pong))
    case Pong => log("Pong!") as Stream.empty
    case Close => log("Close") as Stream(Take.Value(Close), Take.End)
  }
```
This handles the input frames by echoing them, and responds to `Ping` frames as required. It handles `Close` frames by sending a `Close` frame and then terminating the stream with `Take.End`.

I guess there's a case to be made that the library should handle at least `Close` for you, and maybe `Ping/Pong` as well... maybe there is a higher-level API we could add to abstract that away, but given how low-level the rest of the library is I think there needs to be a low-level API where user code receives all the frames and decides what to do.

**Comment by jeremyrsmith** [comment]
I'm not quite sure why the entire server seems to collapse if you don't handle the websocket input frames properly... that's not super great. Will dig into it a bit more. But the good news is that if you do handle them everything seems to work fine. I added an example echo websocket endpoint to the example `TestServer`:  https://github.com/polynote/uzhttp/blob/master/src/test/scala/uzhttp/server/TestServer.scala

**Comment by ghostdogpr** [comment]
It seems to work indeed, thanks! Will try again after your PR is merged to confirm.

**Comment by ghostdogpr** [comment]
@jeremyrsmith I confirm now it works without me handling the input `Close` messages! For the output frames though, if I send `Close` I have to send it wrapped in `Take` and send a `Take.End` afterwards. If I just send `Close` it's in a weird state again. Maybe the library could also take care of that case?

Anyway I now have a fully working uzhttp adapter for Caliban! Usage is by far the simplest of all the adapters. I'll push a PR for it once you release the latest changes.
