### ISSUE TITLE
Support for Sec-WebSocket-Protocol

### ISSUE THREAD

**Issue by ghostdogpr** [polynote/uzhttp#15]
When a WebSocket connection is made with the header `Sec-WebSocket-Protocol`, the server is supposed to send this header back in the response if the protocol is supported.

See: https://tools.ietf.org/html/rfc6455#section-11.3.4
```
The |Sec-WebSocket-Protocol| header field is used in the WebSocket
   opening handshake.  It is sent from the client to the server and back
   from the server to the client to confirm the subprotocol of the
   connection.
```

FYI how it's done in other libraries:
- in http4s, the `WebSocketBuilder` accepts a list of headers that are passed in the response. This is quite flexible.
- in Akka HTTP, it's more specific, there is an explicit `subprotocol: Option[String]` parameter that allows giving the value to use in the `Sec-WebSocket-Protocol` header

**Comment by jeremyrsmith** [comment]
@ghostdogpr The underlying `WebsocketResponse` does take a list of headers, but I've forgotten to allow passing them in the `Response.websocket` constructor. You can work around it for now by using `Response.websocket(req, outputFrames).addHeader("Sec-WebSocket-Protocol", "foo")`, but a PR to specify extra headers on `Response.websocket` (like the other `Response` constructors allow) would be welcome!

**Comment by ghostdogpr** [comment]
Works well! PR incoming.
