### ISSUE TITLE
Test against the latest ZIO snapshot

### ISSUE THREAD

**Issue by iravid** [polynote/uzhttp#22]
Hi @jeremyrsmith, we just merged a significant refactor to ZStream in which chunks are embedded on all streams.

Would be great if you could test uzhttp against the latest snapshot and report back if any issues pop up.

**Comment by jeremyrsmith** [comment]
Thanks for the heads up – I should have noticed this earlier, but now that RC19 is out I'll be working on fixing against the upstream changes there.
