### ISSUE TITLE
Release against ZIO RC19

### ISSUE THREAD

**Issue by KadekM** [polynote/uzhttp#25]
It would be awesome to have RC19 release :)

**Comment by KadekM** [comment]
@jeremyrsmith would you be open to a PR ?

**Comment by jeremyrsmith** [comment]
@KadekM Absolutely would be open to a PR! On first glance, there are some pretty major changes upstream that will have to be dealt with – `Take` is gone, for example, and there are some major changes to `ZSink` which is used for websocket frame parsing.

**Comment by jeremyrsmith** [comment]
@KadekM here's my initial crack at it: #26 any improvements would be welcome!

**Comment by KadekM** [comment]
@jeremyrsmith thanks a lot, I hoped to give it a crack myself =)
